apiVersion: v1
kind: Secret
metadata:
  name: terminal-secret
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
  {{- .Values.terminal.wetty.sshKey | default "nothing" | b64enc | nindent 4  }}
