---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom
    spec:
      serviceAccountName: {{ .Values.terminal.serviceAccount }}
      containers:

      - name: nginx
        image: {{ .Values.proxy.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /data/www
          name: content
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-pid
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 8080

      - name: content
        image: {{ .Values.content.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: GIT_REPO_URL
            value: {{ .Values.content.repoUrl }}
          - name: GIT_REPO_REF
            value: {{ .Values.content.repoRef }}
          - name: ANTORA_PLAYBOOK
            value: {{ .Values.content.antoraPlaybook }}
        volumeMounts:
          - name: user-data
            mountPath: /user_data/
          - name: showroom
            mountPath: /showroom/
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000

      - name: terminal
        image: {{ .Values.terminal.image }}
        imagePullPolicy: IfNotPresent
        args:
          - --base={{ .Values.terminal.wetty.base }}
          - --port=8001
          - --allow-iframe
{{- if .Values.terminal.wetty.autoSshToBastion }}
          - --ssh-host={{ .Values.terminal.wetty.sshHost }}
          - --ssh-port={{ .Values.terminal.wetty.sshPort }}
          - --ssh-user={{ .Values.terminal.wetty.sshUser }}
          - --ssh-auth={{ .Values.terminal.wetty.sshAuth }}
          - --ssh-pass={{ .Values.terminal.wetty.sshPass }}
{{- end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: terminal-secret
            mountPath: /sshkey/ # not implemented
        ports:
         - containerPort: 8001
           protocol: TCP
        resources:
          {{- toYaml .Values.terminal.resources | nindent 10 }}

      volumes:
      - name: showroom
        emptyDir: {}
      - name: user-data
        configMap:
          name: {{ .Values.content.userdataName }}
      - name: content
        configMap:
          name: {{ .Values.home.contentConfig }}
      - configMap:
          defaultMode: 420
          name: showroom-proxy
        name: nginx-config
      - emptyDir: {}
        name: nginx-pid
      - emptyDir: {}
        name: nginx-cache
      - name: terminal-secret
        secret:
          secretName: terminal-secret
