---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom-proxy
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: showroom-proxy
spec:
  to:
    kind: Service
    name: showroom-proxy
  port:
    targetPort: 8081
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
