---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: showroom
spec:
  to:
    kind: Service
    name: showroom
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
