---
apiVersion: v1
kind: Service
metadata:
  name: showroom
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: showroom
