---
apiVersion: v1
kind: Service
metadata:
  name: showroom-proxy
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: showroom
