{{- if not .Values.content.url }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.content.userdataName }}
  namespace: {{ .Values.namespace.name }}
data:
  user_data.yml: |
{{ .Values.content.user_data | indent 4 }}
{{- end }}
