kind: ConfigMap
metadata:
  name: {{ .Values.proxy.nginxConfigMap }}
  namespace: {{ .Values.namespace.name }}
apiVersion: v1
data:
  nginx.conf: |
    #daemon off;
    events {
    }
    error_log /dev/stdout info;
    http {
      include /etc/nginx/mime.types;
      proxy_cache off;
      expires -1;
      proxy_cache_path /dev/null keys_zone=mycache:10m;

      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }

      server {
          listen 8080;

          absolute_redirect off;

          location / {
            index index.html;
            root /data/www;
          }

          location /ocp {

            # not working, don't know why
            # keeps looking for assets on / of the nginx

            proxy_pass https://console.openshift-console:443;
            rewrite ^/ocp/(.*)$ /$1  break;

            expires off;
            proxy_cache off;
            proxy_pass_request_headers on;
            proxy_set_header Accept-Encoding "gzip";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }

          location /content/ {
            proxy_pass http://localhost:8000;
            rewrite ^/content/(.*)$ /$1  break;

            expires off;
            proxy_cache off;
            proxy_pass_request_headers on;
            proxy_set_header Accept-Encoding "gzip";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }

          location ^~ /wetty {
            proxy_pass http://localhost:8001/wetty;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 43200000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
          }
      }
    }
